An error occurred while executing the following cell:
------------------
x = pd.Series(trace_centered["mu_alpha"], name="mu")
y = pd.Series(trace_centered["log_sigma_alpha"], name="log sigma_alpha")
sns.jointplot(x, y, xlim=xlim, ylim=ylim)
plt.suptitle("centered")
plt.savefig("schools8_centered_joint.png", dpi=300)

x = pd.Series(trace_noncentered["mu_alpha"], name="mu")
y = pd.Series(trace_noncentered["log_sigma_alpha"], name="log sigma_alpha")
sns.jointplot(x, y, xlim=xlim, ylim=ylim)
plt.suptitle("noncentered")
plt.savefig("schools8_noncentered_joint.png", dpi=300)
------------------

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_3714/2056599838.py in <module>
      1 x = pd.Series(trace_centered["mu_alpha"], name="mu")
      2 y = pd.Series(trace_centered["log_sigma_alpha"], name="log sigma_alpha")
----> 3 sns.jointplot(x, y, xlim=xlim, ylim=ylim)
      4 plt.suptitle("centered")
      5 plt.savefig("schools8_centered_joint.png", dpi=300)

TypeError: jointplot() takes from 0 to 1 positional arguments but 2 positional arguments (and 2 keyword-only arguments) were given
TypeError: jointplot() takes from 0 to 1 positional arguments but 2 positional arguments (and 2 keyword-only arguments) were given
