An error occurred while executing the following cell:
------------------
import numpy as np
import matplotlib.pyplot as plt


def imshow(img):
    img = img / 2 + 0.5  # unnormalize
    npimg = img.numpy()
    plt.figure(figsize=(10, 10))
    plt.imshow(np.transpose(npimg, (1, 2, 0)))
    plt.show()


# get some random training images
dataiter = iter(dm.train_dataloader())
images, labels = dataiter.next()

# show images
imshow(torchvision.utils.make_grid(images))
label_names = [classes[labels[j]] for j in range(BATCH_SIZE)]
print(label_names)
------------------

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_5488/715302025.py in <module>
     13 # get some random training images
     14 dataiter = iter(dm.train_dataloader())
---> 15 images, labels = dataiter.next()
     16 
     17 # show images

AttributeError: '_MultiProcessingDataLoaderIter' object has no attribute 'next'
AttributeError: '_MultiProcessingDataLoaderIter' object has no attribute 'next'
